### ISSUE TITLE
Updated version or revert flag?

### ISSUE THREAD

**Issue by ourweakness** [n3oxmind/gns3theme#1]
Labbing late last night and I ran this script, but I did not check my versions, I ran this on 2.2.3, and now my gns3-gui package is still holding onto the changes even after a re-install. 

What I've done to try and fix it - 

1. Re-install `gns3-gui` and `gns3-server`
2. Restored `~/.config/GNS3`

Have you given any thoughts to updating this to support newer versions or a way to reverse changes made?

**Comment by n3oxmind** [comment]
> 1. Re-install `gns3-gui` and `gns3-server`
This what should be done to restore the original gns3-gui. I'll consider adding this as an option.
> 2. Restored `~/.config/GNS3`
I think the script already make a back up of your .config/GNS3 files, if not, I'll make sure to fix this and add option to restore them.

I'll take a look this night and see if I can push an updated version of this.

**Comment by n3oxmind** [comment]
Updated!

**Comment by ourweakness** [comment]
Just confirmed - working with 2.2.3

Thank you @n3oxmind !
