### ISSUE TITLE
change color of links

### ISSUE THREAD

**Issue by laimaretto** [n3oxmind/gns3theme#10]
So I've installed following the isntructions. But these changes the theme globally. Is there a chance of modifying certain links widths or colors, individually? As per the github page, it seems so, but I'm not being able of finding where to do it ... :-( ...

I mean, is it possible to change some links to, say red, and some other to blue? Or dashed? etc ... but in the same project?

**Comment by n3oxmind** [comment]
@laimaretto , Based on the original code for gns3-gui. Links color and width are fixed across the project.

`gns3theme` will allow you to change those values (e.g. changing the link color to red/blue, and link width to 3), all links will have the same new color and the same new width.

Here is how to do it,

```sh
 gns3theme[master] ./gns3theme.sh -h
Usage: ./gns3theme.sh --scheme <scheme-name> [OPTIONS] -u <username>
   or: ./gns3theme.sh --scheme <scheme-name> [OPTIONS] -u <username> --opacity <num>
   or: ./gns3theme.sh -u <username> [OPTION]..
OPTIONS:
  --bg			Change primary background color
  --bg2			Change secondary background color
  --fg			Change primary foreground color
  --fg2			Change secondary foreground color
  --tbg			Change toolbar background color
  --sbg			Change selection background color
  --sfg			Change selelction foreground color
  --btn			Change button background color
  --lc			Change ethernet link color. Required reinstall gns3-gui
  --gc			Change grid color. Required reinstall
  --src			Path to gns3-gui source files directory
  --lw			Change ethernet and serial links width, Required reinstall gns3-gui
  -u			Specify username. Manditory option
  -o, --opacity		Apply transparency to gns3 gui. Required reinstall gns3-gui
  -s, --scheme		Change gns3 theme from predefined schemes
  -l, --list-schemes	List gns3 schemes

Run this command only once as a root
  sudo ./gns3theme.sh --install --src /path/to/gns3-gui-source-dir -u <username>		
Install theme from predefined schemes
  ./gns3theme.sh --scheme gruvbox-light -u <username>		
  ./gns3theme.sh --scheme solarized-light -u <username>		
Use the scheme but with different selection color
  ./gns3theme.sh --scheme solarized-light --sbg ef5350 -u <username>		
Install custom scheme
  ./gns3theme.sh  -u <username> --bg 282828 --bg2 323232 --fg FFFFFF --tbg 303030 ..		
  ./gns3theme.sh -u <username> --bg 282828 --bg2 323232 --fg FFFFFF --tbg 303030 -o 0.95 ..		
Change link and grid color
  ./gns3theme.sh  -u <username>  --install --scheme n30x-darkw --lc 939393 --gc 323232	
```

see the last example in the help file. That's how you do it.

**Comment by laimaretto** [comment]
Hi @n3oxmind ! Thanks for the fast response! Yes, I've seen this, and I have indeed applied some coloring to the links as well as different widths, but as you mentioned this applies for the whole project. I was mostly interested in having some particular links with one color and some other links with a different one, but within the same project ... 

But as you have clearly stated, this is not possible ... at least for now (I'm using GNS3 2.2.18).

Hope this will be available in new versions of GNS3 ...

thanks!!
