### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by navaizrael** [n3oxmind/gns3theme#13]
When I try to run the install as root I get this error. 

sed: 1: "/var/folders/zz/zyxvpxv ...": invalid command code f
/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/gns3theme.XXXXXXXX.vQn2Uwru

My Mac is on MACOS Big SUR 11.4.

**Comment by n3oxmind** [comment]
@navaizrael ,  Try to install `gnu-sed` before running the script.

**Comment by navaizrael** [comment]
I did install it.

**Comment by n3oxmind** [comment]
@navaizrael , This happens when `gnu-sed` is not in your PATH. Follow these steps to add it.

1- From brew info get gnu-sed path
```sh
$ brew info gnu-sed
...
GNU "sed" has been installed as "gsed".
If you need to use it as "sed", you can add a "gnubin" directory
to your PATH from your bashrc like:
PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
```
2- Export the PATH from the above command (yours may be different):
```sh
$ export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
```
3- install gns3theme.sh

**Comment by n3oxmind** [comment]
@navaizrael , I re-write the tool in python and fixed few issues. Please install on MacOS and let me know.  No more MacOS dependencies.
