### ISSUE TITLE
GNS3 Theme - Update - Not Really An Issue

### ISSUE THREAD

**Issue by WhatsTheIP** [n3oxmind/gns3theme#14]
Good morning,

As of right now, I'm on GNS3 version 2.2.23, and GNS3 is on version 2.2.26.

Would there be any issues updating to future versions (I believe this GitHub (gns3theme) is based on 2.2.23)?

I didn't want to try and update to test this out in case something breaks, sometimes it takes a bit of time to build from scratch again.

Anyways, still using the dark theme, and by far 1 of my most loved projects to date!

Sorry if this is the proper place to ask the question

**Comment by n3oxmind** [comment]
@WhatsTheIP , I updated the tool and Its should be compatible with GNS3 version >=2.0.0. Its easier now to install and play with colors :).

**Comment by n3oxmind** [comment]
Please test and let me know

**Comment by WhatsTheIP** [comment]
> Please test and let me know

Good morning!

I am able to apply the configuration, but in the interface style the custom drop down only populates when I run GNS3 as root

GNS3 and QT version:
Running GNS3 version 2.2.26 on Linux (64-bit) with Python 3.9.7 Qt 5.15.2 and PyQt 5.15.0.

_____________________________________________________________

Screenshot - 1:
![image](https://user-images.githubusercontent.com/88633281/140284349-04cd2209-a111-4bc7-9d87-9a1ac66022cf.png)

Here is a screenshot as a regular user:

![image](https://user-images.githubusercontent.com/88633281/140284570-f943069c-dbdb-454c-b7c3-e6dc8bc88381.png)

___________________________________________________________

This is the path of my gns3 executable file, I am not sure if this would have anything to do with it:
- /home/gns3s3/.local/bin

**Comment by WhatsTheIP** [comment]
Good morning n3oxmind,

I fixed the issue, the path was the issue! Prior to you writing back to me I updated GNS3 to 2.2.26 but Fedora is a few releases behind in the repo

So I updated to 2.2.26 using the following command:
- pip3 gns3-gui gns3-server

____________________________________________________________

When you wrote back to me, I went to test the update to confirm if 2.2.26 worked, but it didn't which is when I notice when I opened GNS3 it was located in that strange path I added at the top ^:
- /home/gns3s3/.local/bin

Anyways, what confirmed it was then I was able to open GNS3 via root, and from my understanding root launches GNS3 from a different path (which pip3 doesn't mess with)

Next, I moved the file from GNS3 to local/bin because I thought that's where I originally saw the install (it's where my servers have it installed)

Re-ran your script and it removed it from the local/bin and noticed the output from the gns3-gui script was installing GNS3 somewhere else
_________________________________________________________

Anyways, I deleted gns3 from Fedora doing the following:
- sudo dnf remove gns3-gui gns3-server
- sudo pip3 uninstall gns3-gui gns3-server

Went back to the folder which contains:
- gns3-server-master, ran sudo python3 setup install
- gns3-gui-master, ran sudo python3 setup install

Then went to the folder where I have gns3theme-master:
- ran the proper commands

GNS3:
- Relaunched, and the drop-down now appears!

Thank you for the hard work!

**Comment by WhatsTheIP** [comment]
![image](https://user-images.githubusercontent.com/88633281/140289273-797ab35c-81df-4f1a-b984-7a65398f1e48.png)

**Comment by n3oxmind** [comment]
@WhatsTheIP , Thank you for the test. I'm very glad that it worked for you. Have fun!.

Closing this issue.
