### ISSUE TITLE
No Custom option under "Interface Style"

### ISSUE THREAD

**Issue by g-h-97** [n3oxmind/gns3theme#15]
Hi dev,

Is this project still on active development ? I guess it's not compatible with the latest gn3-gui release, since the "Interface style" drop down menu doesn't show the "Custom" option.

Edit: It seems that the "Custom" option is not appearing on Voidlinux only for some reason, I tried installing it on Archlinux and the option is there but it's not taking effect since the theme turns completely white as soon as I select "Custom". Any ideas ?

**Comment by g-h-97** [comment]
@n3oxmind would really appreciate your assistance on this case, It seems that I can't even downgrade to an older version due to some python dependencies. I use Voidlinux as my daily driver, and the default themes are really painful to look at.

The issue is that during the installation, no errors or warnings are generated so there is nothing to trace.
![2022-07-19_06-04](https://user-images.githubusercontent.com/61669101/179736049-0674b3f1-e936-48aa-870f-ea2f395892e0.png)

**Comment by g-h-97** [comment]
Finally managed to solve it !

For some reason the custom (patched) gns3-gui was not getting installed under the right directory `/usr/lib/python3.10/site-packages/`. I had to manually delete all related packages `doas rm -rf gns3*` from there and reinstall `gns3theme`, only then it worked as expected. 
![2022-07-19_06-56](https://user-images.githubusercontent.com/61669101/179744338-ee51d311-d350-4a91-ab94-69728ab96892.png)

I'm still not sure why, but the `Cleanup` function is not doing what it's supposed to do.

**Comment by n3oxmind** [comment]
@g-h-97 , Glad you figured it out. I'll check the cleanup function. Thanks for reporting that and have fun.

**Comment by g-h-97** [comment]
@n3oxmind Thank you !

The cleanup function was trying to use `pip` to uninstall `gns3-gui` and the old installation wasn't even installed using `pip` (in fact I don't even have `pip` installed). In my case I installed it using my distro's package manager.

So, the line number 151 (bellow) was failing to uninstall `gns3-gui` correctly.
`output = subprocess.run(['python3', '-m', 'pip', 'uninstall', 'gns3-gui', '-y'], stderr=subprocess.PIPE)`

I hope that will help you troubleshoot the issue.
