### ISSUE TITLE
Link color not changing

### ISSUE THREAD

**Issue by g-h-97** [n3oxmind/gns3theme#16]
Hi guys,

As I pointed out in the title, the link color is not getting applied (Links are completely black). And the CSS file does not list the color anywhere.

Would appreciate any help. Thank you.

**Comment by n3oxmind** [comment]
@g-h-97 , I think the current version of GNS3 offers this feature now. That's why I removed it. Please check the latest GNS3 version and let me know. Suppose GNS3 does not support changing link color permanently; I'll work on adding it back this weekend.

**Comment by g-h-97** [comment]
It does, but in a per link basis. There is no option on the entire gui to set a permanent link color. I truly appreciate it dev, please close this case ASA you're done.

Thank you @n3oxmind,

**Comment by g-h-97** [comment]
Hello @n3oxmind, 

Any update on this request ?

**Comment by n3oxmind** [comment]
Hi @g-h-97, I'm a little burned out at work this year. I'm looking at the code to see if I can push an update regarding this issue. Please note that link color will only apply to a new project created after applying the custom theme. The link color for an existing project won't change.

**Comment by n3oxmind** [comment]
@g-h-97, You should be able to change the link color now. Try it and let me know.
`sudo ./gns3theme.py --install /path/to/gns3/installation/directory -u $USER  --scheme <colorscheme> --lc ffffff `

Make sure to point the command to your gns3 installation directory. Check read me for more details.

**Comment by g-h-97** [comment]
@n3oxmind, thanks for adding it back again. It's working as expected, however, I encountered some issues installing the last master branch so I decided to fix them and opened a pull request instead of opening another issue, please feel free either merge or fix them on you master branch directly.

Thanks again dev, appreciate you work,
