### ISSUE TITLE
Theme not working

### ISSUE THREAD

**Issue by rick0x00** [n3oxmind/gns3theme#20]
I imagine that I did the procedure correctly, as shown in the attached images, without returning errors, but nothing happened, the "custom" theme is actually the same as the "classic" theme, I have already tested it with other themes, but it is not working as it should.

[imagem1](https://media.mcdn.co/embedded/636855a4fdc6a7e3f41e0474?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9tZWRpYS5tY2RuLmNvL2VtYmVkZGVkLzYzNjg1NWE0ZmRjNmE3ZTNmNDFlMDQ3NCIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MzMyMjUzODIzMTB9fX1dfQ__&Key-Pair-Id=APKAJDKBVMGXNCXPKSSQ&Signature=MszJ4gtYNsHr-770K4cjxK0Mcw02StikBVtMK6Z2vWm2zRdhZA7c~ESTuwpUvyaDwHziGB310MA4yNQl3DS4Ho6BtFB4Ux8Qqed~niKqZuWLtEMoKZHn-KmiWdCb332~PCeLcRjt3wylDJpjgpyit380l4RFykSvFc90OyJRFKkcocp7D~rqhRZTUk5lkDvN0-xcvIxzgnCYudTUxcwCfbyPAORIGUsFyF6cUvTdnfeILGj8RQjwH2gmkwVwwCPZkifUHcclmBIDA-MWi7jU7DnXhPiX69G680mDiAX-b9CKfye8EcY7tICXpy3oIXcr8muq3kAicTs-Gz010RaQgw__)

[imagem2](https://media.mcdn.co/embedded/6368556ffdc6a7e3f41dda1e?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9tZWRpYS5tY2RuLmNvL2VtYmVkZGVkLzYzNjg1NTZmZmRjNmE3ZTNmNDFkZGExZSIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MzMyMjUzODIzMTB9fX1dfQ__&Key-Pair-Id=APKAJDKBVMGXNCXPKSSQ&Signature=dCXoZvyH9hoiQeg5l8DBBjO2gayUp~BhgnC5EKZuUVtdK2kHJ~Ay7RKRGbMogfBMlC3R6gb5LpsI0RRk-BwLeSYSdVMGneC32lekgsAbGtmMlmFE-D1793F5wT979BfdmNlR-yIb7S4wizUk5MEPZHwZwjAOrVOmQeC7dCtdNM04PTc5IoXTvD~bmBo5GlTLCSQ2xGVsnE9d-TCBQIyJVd4eXAunGoT5BGCG-IeIz6H1hoRfWE6DB5vaZKvOzXdAaU6LiPSe4zrRB4g6Wr77soyiP5S5ucjMMd526dAAVxajZzrsgBjVOfP2mpSE3dVYqzvaMqt9sfSIq7RNE6QthQ__)

**Comment by n3oxmind** [comment]
@rick0x00, Thanks for reporting this. I took a quick look and found out that I forgot to fix the broken path to the custom theme. The issue was fixed in the new patch release. [v4.0.3](https://github.com/n3oxmind/gns3theme/archive/refs/tags/v4.0.3.tar.gz). Test and let me know.

**Comment by rick0x00** [comment]
> @rick0x00, Thanks for reporting this. I took a quick look and found out that I forgot to fix the broken path to the custom theme in the last merge. The issue was fixed in the new patch release. [v4.0.3](https://github.com/n3oxmind/gns3theme/archive/refs/tags/v4.0.3.tar.gz). Test and let me know.

thank you very much for the answer, I did the tests here and it worked after reinstalling the gns3-gui, only the colors of the themes that were different from the images presented, but soon I customized it as I wanted
