### ISSUE TITLE
Current GNS3 Version issue

### ISSUE THREAD

**Issue by danielbostock** [n3oxmind/gns3theme#5]
Hi,

Thanks firstly for making what look like some awesome themes!

Well I can kinda see the theme when I install them, the problem seems to be that it only works for version 2.2.3, where the current version is 2.2.16 that my server is running.

I am guessing every time GNS3 releases an update you need to update your gns3-gui contents? Is there a way to install a scheme with out replacing all the GNS3 core files so it is independent of the version as I see this being a continual issue and I would really like to use these themes as my current dark theme for KDE makes the text impossible to read unless I switch to classic built in theme.

Thanks.

**Comment by n3oxmind** [comment]
You're right. gns3-gui does not support custom stylesheets as far as I know. Its been a while since the last time I've updated this script.
Having a script that work for all versions is doable. I'll take a look and update if possible.

**Comment by danielbostock** [comment]
@n3oxmind - Thanks mate, appreciate you looking into this!

**Comment by n3oxmind** [comment]
@danielbostock - I've updated the script and removed dependencies. Its should be version independent now.

give it a try, and let me know if you have any issue.

-have fun

**Comment by danielbostock** [comment]
Hey @n3oxmind 

Thanks for the update.

I have pulled latest update from the repo, and then have tried running the first part of the setup. I get the following error. I am running with GNS3 through a pip3 packaged install as my distro is Manjaro. 

```bash
 ✘ daniel@danpc  ~/GNS3-Dev/gns3theme   master  sudo ./gns3theme.sh --install --src /usr/bin/gns3-gui-2.2.16
Directory does not exist '/usr/bin/gns3-gui-2.2.16'
```

I don't see a folder for the specific version of my install, and if I go to /usr/bin and run ```sudo gns3``` I can execute and open GNS3 directly from there.

I also just tried running the same scheme install process from your previous version which would be the next step after the install step you have added for this new version. It completes with no errors, but the theme is not accessible in my preferences whether I run gns3 as my user or as root.

Not sure what I am doing wrong here sorry mate!

Thanks.

**Comment by n3oxmind** [comment]
@danielbostock, --src should be the path to the extracted source code of gns3-gui-2.2.16

download this https://github.com/GNS3/gns3-gui/archive/v2.2.16.tar.gz
extract using  `tar -xavf ~/Downloads/gns3-gui-2.2.16`
run ` sudo ./gns3theme.sh --install --src ~/Downloads/gns3-gui-2.2.16`

**Comment by danielbostock** [comment]
@n3oxmind - Yep that worked, great job mate GNS3 is now readable and looks really good!!

Thanks heaps!!
