### ISSUE TITLE
Does it work on Windows?

### ISSUE THREAD

**Issue by quietwish** [n3oxmind/gns3theme#9]
I searched the whole internelt, and you are the only person contribute on dark mode for GNS3, that's awesome!

**Comment by n3oxmind** [comment]
@quietwish , currently its Linux only (sorry). I'll tag this issue as a feature request and work on it later on my free time.

**Comment by navaizrael** [comment]
Hi, I really want this to because I like my Dark mode on my macbook Pro, big Sur. I get this error when running the shell script.
mktemp: option requires an argument -- t. 
Thanks.

**Comment by n3oxmind** [comment]
@navaizrael , open this as a new issue with the title "Request MacOS support". I'll be pushing an update within a few minutes. Currently, Testing on my work Mac.

**Comment by n3oxmind** [comment]
@navaizrael , I've added support to MacOS. Try it and let me know
https://github.com/n3oxmind/gns3theme/releases/tag/v3.0.3

**Comment by mangkoran** [comment]
Does Windows already supported? I see that you only have released for macOS in this issue.
